name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install LaTeX
        run: sudo apt-get update && sudo apt-get install texlive-base texlive-latex-extra texlive-extra-utils texlive-fonts-recommended texlive-latex-recommended texlive-lang-polish texlive-bibtex-extra biber latexmk
      - name: Build LaTeX document
        run: latexmk -synctex=1 -interaction=nonstopmode -file-line-error -pdf -shell-escape -bibtex thesis.tex
      - name: generate SHA256 checksum
        run: sha256sum thesis.pdf > thesis.pdf.sha256
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            thesis.pdf
            thesis.pdf.sha256
